apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: rushidonga/task-app:v2
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks
          volumeMounts:
            - mountPath: /app/tasks
              name: tasks-volume
      volumes:  
        - name: tasks-volume
          hostPath:
            path: /tasks
            type: DirectoryOrCreate